/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyelakhirfisdas;

import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;

import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author Sandi
 */
public class MainFrame extends javax.swing.JFrame {
    
    private DCMotorFrame frame;
    private DCMotorFormula formula;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        initComponentsUser();
    }
    
    private void initComponentsUser(){
        frame = new DCMotorFrame();
        formula = new DCMotorFormula();
        
        frame.addWindowListener(new WindowAdapter() {

            public void windowClosed(WindowEvent evt) {
                setVisible(true);

            }
        });
        
        arusTextField.setDocument(new LengthRestrictedDocument(4));
        lebarTextField.setDocument(new LengthRestrictedDocument(4));
        medanTextField.setDocument(new LengthRestrictedDocument(4));
        panjangTextField.setDocument(new LengthRestrictedDocument(4));
        rTextField.setDocument(new LengthRestrictedDocument(4));
        
        setSize(250,260);
    }
    
    /**
     * Inner Kelas untuk membatasi jumlah inputan dalam TextField
     * Copas dari StackOverflow :3
     */
    private final class LengthRestrictedDocument extends PlainDocument {

        private final int limit;

         public LengthRestrictedDocument(int limit) {
            this.limit = limit;
        }

        @Override
        public void insertString(int offs, String str, AttributeSet a)
            throws BadLocationException {
          if (str == null)
            return;

          if ((getLength() + str.length()) <= limit) {
            super.insertString(offs, str, a);
          }
        }
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        arusLabel = new javax.swing.JLabel();
        arusTextField = new javax.swing.JTextField();
        medanLabel = new javax.swing.JLabel();
        medanTextField = new javax.swing.JTextField();
        lebarLabel = new javax.swing.JLabel();
        lebarTextField = new javax.swing.JTextField();
        panjangLabel = new javax.swing.JLabel();
        panjangTextField = new javax.swing.JTextField();
        rLabel = new javax.swing.JLabel();
        rTextField = new javax.swing.JTextField();
        simulasiButton = new javax.swing.JButton();
        arahI = new javax.swing.JCheckBox();
        arahB = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulasi DC Motor");
        setResizable(false);
        setSize(new java.awt.Dimension(350, 250));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        arusLabel.setText("I");
        getContentPane().add(arusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, 14, -1));

        arusTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arusTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(arusTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 11, 50, -1));

        medanLabel.setText("B");
        getContentPane().add(medanLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 46, 30, -1));
        getContentPane().add(medanTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 43, 50, -1));

        lebarLabel.setText("Lebar");
        getContentPane().add(lebarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 14, 37, -1));
        getContentPane().add(lebarTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 11, 58, -1));

        panjangLabel.setText("Panjang");
        getContentPane().add(panjangLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 46, -1, -1));
        getContentPane().add(panjangTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 43, 56, -1));

        rLabel.setText("R");
        getContentPane().add(rLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 84, 26, -1));
        getContentPane().add(rTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 52, -1));

        simulasiButton.setText("OK");
        simulasiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulasiButtonActionPerformed(evt);
            }
        });
        getContentPane().add(simulasiButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        arahI.setText("Arah I CW");
        getContentPane().add(arahI, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        arahB.setText("Arah B CW");
        getContentPane().add(arahB, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void arusTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arusTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arusTextFieldActionPerformed

    private void simulasiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulasiButtonActionPerformed
        setVisible(false);
        
        formula.b = Double.parseDouble(medanTextField.getText());
        formula.i = Double.parseDouble(arusTextField.getText());
        formula.panjang = Double.parseDouble(panjangTextField.getText());
        formula.lebar = Double.parseDouble(lebarTextField.getText());
        formula.r = Double.parseDouble(rTextField.getText());
        
        formula.arahB = arahB.isSelected();
        formula.arahI = arahI.isSelected();
        
        frame.prepareRotation(formula.computeW(), formula.arahB, formula.arahI);
        frame.setVisible(true);
        
    }//GEN-LAST:event_simulasiButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox arahB;
    private javax.swing.JCheckBox arahI;
    private javax.swing.JLabel arusLabel;
    private javax.swing.JTextField arusTextField;
    private javax.swing.JLabel lebarLabel;
    private javax.swing.JTextField lebarTextField;
    private javax.swing.JLabel medanLabel;
    private javax.swing.JTextField medanTextField;
    private javax.swing.JLabel panjangLabel;
    private javax.swing.JTextField panjangTextField;
    private javax.swing.JLabel rLabel;
    private javax.swing.JTextField rTextField;
    private javax.swing.JButton simulasiButton;
    // End of variables declaration//GEN-END:variables
}
